<a href="https://colab.research.google.com/github/wahyukusuma/singleaccelerometer/blob/master/ActivityRecognitionPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import numpy as np
from IPython.display import display
import matplotlib.pyplot as plt
#
import matplotlib.gridspec as gridspec
import itertools
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from mlxtend.classifier import EnsembleVoteClassifier
from mlxtend.plotting import plot_decision_regions
%matplotlib inline

In [0]:
from sklearn.utils import shuffle

train = pd.read_csv("drive/My Drive/1HumanActivity/HAPT/train.csv")
test = pd.read_csv("drive/My Drive/1HumanActivity/HAPT/test.csv")

train = shuffle(train)
test = shuffle(test)

display(train.head())

print (train.shape)
print "\n"
#print (test.shape)

subject_training_data = train['subject']
subject_testing_data = test['subject']

training_labels = train['Activity']
testing_labels = test['Activity']

train = train.drop(['subject', 'Activity'], axis=1)
test = test.drop(['subject', 'Activity'], axis=1)

print "Training data consists of {} instances of data with {} total features".format(train.shape[0], train.shape[1])
print "Training data includes value counts of\n", training_labels.value_counts()
print "\n"
print "Testing data consists of {} instances of data".format(test.shape[0])
print "Testing data includes value counts of\n", testing_labels.value_counts()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  subject            Activity
6722           0.280079          -0.016785  ...       29              LAYING
1276           0.188511           0.014950  ...        6  WALKING_DOWNSTAIRS
513            0.274418          -0.056770  ...        3    WALKING_UPSTAIRS
294            0.190223          -0.038897  ...        1             WALKING
1506           0.282416          -0.008007  ...        7             SITTING

[5 rows x 563 columns]

(7352, 563)


Training data consists of 7352 instances of data with 561 total features
Training data includes value counts of
LAYING                1407
STANDING              1374
SITTING               1286
WALKING               1226
WALKING_UPSTAIRS      1073
WALKING_DOWNSTAIRS     986
Name: Activity, dtype: int64


Testing data consists of 2947 instances of data
Testing data includes value counts of
LAYING                537
STANDING              532
WALKING               496
SITTING               491
WALKING_UPSTAIRS      471
WALKING_DOWNSTAIRS    420
Name: Activity, dtype: int64


In [0]:
numerics = ['int16','int32','int64','float16','float32','float64']
numerical_vars = list(train.select_dtypes(include=numerics).columns)
X_train = train#[numerical_vars]
X_train.shape
X_train.head()

tBodyAcc-mean()-X  ...  angle(Z,gravityMean)
6722           0.280079  ...             -0.428795
1276           0.188511  ...              0.023257
513            0.274418  ...              0.110192
294            0.190223  ...              0.104145
1506           0.282416  ...             -0.044470

[5 rows x 561 columns]

In [0]:
numerical_vars = list(test.select_dtypes(include=numerics).columns)
X_test = test#[numerical_vars]
X_test.shape
X_test.head()

tBodyAcc-mean()-X  ...  angle(Z,gravityMean)
607            0.230884  ...             -0.040316
1465           0.205415  ...              0.039687
1230           0.295573  ...             -0.231813
2170           0.278534  ...              0.180740
2818           0.277026  ...              0.001620

[5 rows x 561 columns]

In [0]:
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

le = LabelEncoder()
le = le.fit(["WALKING", "WALKING_UPSTAIRS", "WALKING_DOWNSTAIRS", "SITTING", "STANDING", "LAYING"])
#le = le.fit(["1", "2", "3", "4", "5", "6"])
enc_training_labels = le.transform(training_labels)
enc_testing_labels = le.transform(testing_labels)

In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier 

dt = DecisionTreeClassifier()
rf = RandomForestClassifier()
xt = ExtraTreesClassifier()
kn = KNeighborsClassifier()
lr = LogisticRegression(random_state=0)
svc = SVC(random_state=0, probability=True)
eclf = EnsembleVoteClassifier(clfs=[dt, rf, xt, kn, lr, svc],
                              weights=[2, 1, 1, 1, 1, 1], voting='soft')

def evaluateclf(clf):
    scores = cross_val_score(clf, X_train, enc_training_labels)
    avg = scores.mean()
    return "performances: {}, \nAverage: {}".format(scores, avg)

print "Decision Tree {}".format(evaluateclf(dt))
print "Random Forest {}".format(evaluateclf(rf))
print "Extra Trees {}".format(evaluateclf(xt))
print "K Neighbors {}".format(evaluateclf(kn))
print "Logistic Regression {}".format(evaluateclf(lr))
print "SVC {}".format(evaluateclf(svc))
print "EnsembleVoteClassifier {}".format(evaluateclf(eclf))

Decision Tree performances: [0.93841762 0.93270799 0.93872549], 
Average: 0.936617033981
Random Forest performances: [0.97226754 0.96818923 0.96446078], 
Average: 0.968305851432
Extra Trees performances: [0.97145188 0.96615008 0.96323529], 
Average: 0.966945750568
K Neighbors performances: [0.96696574 0.96288744 0.95955882], 
Average: 0.963137334869
Logistic Regression performances: [0.98572594 0.98205546 0.98325163], 
Average: 0.983677678974
SVC performances: [0.94535073 0.94004894 0.93300654], 
Average: 0.939468736561
EnsembleVoteClassifier performances: [0.98205546 0.97471452 0.9746732 ], 
Average: 0.977147728767


In [0]:
import sklearn.metrics as met
def model_build(model):
    model.fit(X_train, enc_training_labels)
    return model

# helper function to handle evaluation
def model_eval(model):
    pred = model.predict(X_test)
    print 'Accuracy:\n-----------------------------'
    print met.accuracy_score(enc_testing_labels, pred)
    print '\nConfusion Matrix:\n-----------------------------'
    print met.confusion_matrix(enc_testing_labels, pred)
    print '\nClassification Report:\n-----------------------------'
    print met.classification_report(enc_testing_labels, pred)

In [0]:
set(enc_training_labels) - set(enc_testing_labels)

set()

In [0]:
knn = model_build(KNeighborsClassifier())
model_eval(knn)

In [0]:
print 'DecisionTreeClassifier:\n-----------------------------'
dt = model_build(dt)
model_eval(dt)
print 'RandomForestClassifier:\n-----------------------------'
rf = model_build(rf)
model_eval(rf)
print 'ExtraTreesClassifier:\n-----------------------------'
xt = model_build(xt)
model_eval(xt)
print 'KNeighborsClassifier:\n-----------------------------'
knn = model_build(kn)
model_eval(knn)
print 'LogisticRegression:\n-----------------------------'
lr = model_build(lr)
model_eval(lr)
print 'SVC\n-----------------------------'
svc = model_build(svc)
model_eval(svc)
print 'EnsembleVoteClassifier:\n-----------------------------'
eclf = model_build(eclf)
model_eval(eclf)


DecisionTreeClassifier:
-----------------------------
Accuracy:
-----------------------------
0.8676620291822192

Confusion Matrix:
-----------------------------
[[537   0   0   0   0   0]
 [  0 375 116   0   0   0]
 [  0  76 456   0   0   0]
 [  0   0   0 462  23  11]
 [  0   0   0  15 356  49]
 [  0   0   0  65  35 371]]

Classification Report:
-----------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       537
           1       0.83      0.76      0.80       491
           2       0.80      0.86      0.83       532
           3       0.85      0.93      0.89       496
           4       0.86      0.85      0.85       420
           5       0.86      0.79      0.82       471

   micro avg       0.87      0.87      0.87      2947
   macro avg       0.87      0.86      0.86      2947
weighted avg       0.87      0.87      0.87      2947

RandomForestClassifier:
-----------------------------
Accuracy:
--------------

# **Test Feature Selection**

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

In [0]:
train = pd.read_csv("drive/My Drive/1HumanActivity/HAPT/train.csv")
test = pd.read_csv("drive/My Drive/1HumanActivity/HAPT/test.csv")
train.shape
test.shape
train.head()
test.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  subject  Activity
0           0.257178          -0.023285  ...        2  STANDING
1           0.286027          -0.013163  ...        2  STANDING
2           0.275485          -0.026050  ...        2  STANDING
3           0.270298          -0.032614  ...        2  STANDING
4           0.274833          -0.027848  ...        2  STANDING

[5 rows x 563 columns]

In [0]:
numerics = ['int16','int32','int64','float16','float32','float64']
numerical_vars = list(train.select_dtypes(include=numerics).columns)
train = train[numerical_vars]
train.shape
train.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  angle(Z,gravityMean)  subject
0           0.288585          -0.020294  ...             -0.058627        1
1           0.278419          -0.016411  ...             -0.054317        1
2           0.279653          -0.019467  ...             -0.049118        1
3           0.279174          -0.026201  ...             -0.047663        1
4           0.276629          -0.016570  ...             -0.043892        1

[5 rows x 562 columns]

In [0]:
numerics = ['int16','int32','int64','float16','float32','float64']
numerical_vars = list(test.select_dtypes(include=numerics).columns)
test = test[numerical_vars]
test.shape
test.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  angle(Z,gravityMean)  subject
0           0.257178          -0.023285  ...             -0.057978        2
1           0.286027          -0.013163  ...             -0.083898        2
2           0.275485          -0.026050  ...             -0.079346        2
3           0.270298          -0.032614  ...             -0.077108        2
4           0.274833          -0.027848  ...             -0.073857        2

[5 rows x 562 columns]

In [0]:
scaler = StandardScaler()
scaler.fit(train.fillna(0))

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

## Select Feature with lasso (L1)

In [0]:
sel_ = SelectFromModel(LogisticRegression(C=1, penalty='l1'))
sel_.fit(scaler.transform(train.fillna(0)), enc_training_labels)

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  


SelectFromModel(estimator=LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
        max_features=None, norm_order=1, prefit=False, threshold=None)

In [0]:
sel_.get_support()

array([ True,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True, False, False,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [0]:
selected_feat = train.columns[(sel_.get_support())]
print('total features: {}'.format((train.shape[1])))
print('selected features: {}'.format(len(selected_feat)))
print('features with coefficients shrank to zero: {}'.format(
      np.sum(sel_.estimator_.coef_ == 0)))

total features: 562
selected features: 501
features with coefficients shrank to zero: 1351


In [0]:
np.sum(sel_.estimator_.coef_ == 0)

1351

In [0]:
removed_feats = train.columns[(sel_.estimator_.coef_ == 0).ravel().tolist()]
removed_feats

In [0]:
X_train_selected = sel_.transform(train.fillna(0))
X_test_selected = sel_.transform(test.fillna(0))
X_train_selected.shape, X_test_selected.shape

((7352, 501), (2947, 501))

In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier 

dt = DecisionTreeClassifier()
rf = RandomForestClassifier()
xt = ExtraTreesClassifier()
kn = KNeighborsClassifier()
lr = LogisticRegression(random_state=0)
svc = SVC(random_state=0, probability=True)
eclf = EnsembleVoteClassifier(clfs=[dt, rf, xt, kn, lr, svc],
                              weights=[2, 1, 1, 1, 1, 1], voting='soft')

def evaluateclf(clf):
    scores = cross_val_score(clf, X_train_selected, enc_training_labels)
    avg = scores.mean()
    return "performances: {}, \nAverage: {}".format(scores, avg)

print "Decision Tree {}".format(evaluateclf(dt))
print "Random Forest {}".format(evaluateclf(rf))
print "Extra Trees {}".format(evaluateclf(xt))
print "K Neighbors {}".format(evaluateclf(kn))
print "Logistic Regression {}".format(evaluateclf(lr))
print "SVC {}".format(evaluateclf(svc))
print "EnsembleVoteClassifier {}".format(evaluateclf(eclf))

Decision Tree performances: [0.15375204 0.15905383 0.18014706], 
Average: 0.16431764386
Random Forest performances: [0.16680261 0.18352365 0.17606209], 
Average: 0.175462785259
Extra Trees performances: [0.17169657 0.1680261  0.17973856], 
Average: 0.17315374582
K Neighbors performances: [0.15742251 0.16435563 0.18178105], 
Average: 0.167853062015
Logistic Regression performances: [0.17414356 0.16231648 0.18504902], 
Average: 0.173836350745
SVC performances: [0.1908646  0.18841762 0.18218954], 
Average: 0.187157253694
EnsembleVoteClassifier performances: [0.15497553 0.15783034 0.19035948], 
Average: 0.167721783294


## Select Feature with ridge (L2)

In [0]:
train = pd.read_csv("drive/My Drive/1HumanActivity/HAPT/train.csv")
test = pd.read_csv("drive/My Drive/1HumanActivity/HAPT/test.csv")
numerics = ['int16','int32','int64','float16','float32','float64']
numerical_vars = list(train.select_dtypes(include=numerics).columns)
X_train = train[numerical_vars]
X_train.shape
X_train.head()
numerical_vars = list(test.select_dtypes(include=numerics).columns)
X_test = test[numerical_vars]
X_test.shape
X_test.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  angle(Z,gravityMean)  subject
0           0.257178          -0.023285  ...             -0.057978        2
1           0.286027          -0.013163  ...             -0.083898        2
2           0.275485          -0.026050  ...             -0.079346        2
3           0.270298          -0.032614  ...             -0.077108        2
4           0.274833          -0.027848  ...             -0.073857        2

[5 rows x 562 columns]

In [0]:
l1_logit = LogisticRegression(C=1, penalty='l2')
l1_logit.fit(scaler.transform(X_train.fillna(0)), enc_training_labels)

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  


LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [0]:
sel_.get_support()

array([ True,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True, False, False,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [0]:
selected_feat = X_train.columns[(sel_.get_support())]
print('total features: {}'.format((X_train.shape[1])))
print('selected features: {}'.format(len(selected_feat)))
print('features with coefficients shrank to zero: {}'.format(
      np.sum(sel_.estimator_.coef_ == 0)))

total features: 562
selected features: 501
features with coefficients shrank to zero: 1351


In [0]:
np.sum(sel_.estimator_.coef_ == 0)

1351

In [0]:
selected_feat= X_train.columns[(sel.get_support())]
len(selected_feat)

236

In [0]:
removed_feats = X_train.columns[(sel_.estimator_.coef_ == 0).ravel().tolist()]
removed_feats

In [0]:
X_train_selected = sel_.transform(X_train.fillna(0))
X_test_selected = sel_.transform(X_test.fillna(0))
X_train_selected.shape, X_test_selected.shape

((7352, 501), (2947, 501))

In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier 

dt = DecisionTreeClassifier()
rf = RandomForestClassifier()
xt = ExtraTreesClassifier()
kn = KNeighborsClassifier()
lr = LogisticRegression(random_state=0)
svc = SVC(random_state=0, probability=True)
eclf = EnsembleVoteClassifier(clfs=[dt, rf, xt, kn, lr, svc],
                              weights=[2, 1, 1, 1, 1, 1], voting='soft')

def evaluateclf(clf):
    scores = cross_val_score(clf, X_train_selected, enc_training_labels)
    avg = scores.mean()
    return "performances: {}, \nAverage: {}".format(scores, avg)

print "Decision Tree {}".format(evaluateclf(dt))
print "Random Forest {}".format(evaluateclf(rf))
print "Extra Trees {}".format(evaluateclf(xt))
print "K Neighbors {}".format(evaluateclf(kn))
print "Logistic Regression {}".format(evaluateclf(lr))
print "SVC {}".format(evaluateclf(svc))
print "EnsembleVoteClassifier {}".format(evaluateclf(eclf))

Decision Tree performances: [0.15212072 0.17006525 0.18586601], 
Average: 0.169350661236
Random Forest performances: [0.18964111 0.158646   0.16748366], 
Average: 0.171923590897
Extra Trees performances: [0.18760196 0.17699837 0.17034314], 
Average: 0.17831448784
K Neighbors performances: [0.15742251 0.16435563 0.18178105], 
Average: 0.167853062015
Logistic Regression performances: [0.17414356 0.16231648 0.18504902], 
Average: 0.173836350745
SVC performances: [0.1908646  0.18841762 0.18218954], 
Average: 0.187157253694
EnsembleVoteClassifier performances: [0.15946166 0.16190865 0.18464052], 
Average: 0.168670277609


## Select Feature with Random Forest

In [0]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

In [0]:
numerics = ['int16','int32','int64','float16','float32','float64']
numerical_vars = list(train.select_dtypes(include=numerics).columns)
train = train.drop(['subject', 'Activity'], axis=1)
test = test.drop(['subject', 'Activity'], axis=1)
X_train = train#[numerical_vars]
X_train.shape
X_train.head()
numerical_vars = list(test.select_dtypes(include=numerics).columns)
X_test = test#[numerical_vars]
X_test.shape
X_test.head()

tBodyAcc-mean()-X  ...  angle(Z,gravityMean)
0           0.257178  ...             -0.057978
1           0.286027  ...             -0.083898
2           0.275485  ...             -0.079346
3           0.270298  ...             -0.077108
4           0.274833  ...             -0.073857

[5 rows x 561 columns]

In [0]:
sel = SelectFromModel(RandomForestClassifier(n_estimators = 100))
sel.fit(X_train, enc_training_labels)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
        max_features=None, norm_order=1, prefit=False, threshold=None)

In [0]:
selected_feat= X_train.columns[(sel.get_support())]
len(selected_feat)

238

In [0]:
print(selected_feat)

Index([u'tBodyAcc-mean()-X', u'tBodyAcc-mean()-Y', u'tBodyAcc-mean()-Z',
       u'tBodyAcc-max()-Y', u'tBodyAcc-iqr()-Z', u'tBodyAcc-entropy()-X',
       u'tBodyAcc-entropy()-Y', u'tBodyAcc-entropy()-Z',
       u'tBodyAcc-arCoeff()-X,1', u'tBodyAcc-arCoeff()-X,2',
       ...
       u'fBodyBodyGyroJerkMag-meanFreq()', u'fBodyBodyGyroJerkMag-skewness()',
       u'fBodyBodyGyroJerkMag-kurtosis()', u'angle(tBodyAccMean,gravity)',
       u'angle(tBodyAccJerkMean),gravityMean)',
       u'angle(tBodyGyroMean,gravityMean)',
       u'angle(tBodyGyroJerkMean,gravityMean)', u'angle(X,gravityMean)',
       u'angle(Y,gravityMean)', u'angle(Z,gravityMean)'],
      dtype='object', length=238)


In [0]:
#pd.series(sel.estimator_,feature_importances_,ravel()).hist()

In [0]:
X_train_selected = sel_.transform(X_train.fillna(0))
X_test_selected = sel_.transform(X_test.fillna(0))
X_train_selected.shape, X_test_selected.shape

In [0]:
columnsData = X_train.loc[ : , selected_feat]

In [0]:
columnsData.head()

tBodyAcc-mean()-X  ...  angle(Z,gravityMean)
0           0.288585  ...             -0.058627
1           0.278419  ...             -0.054317
2           0.279653  ...             -0.049118
3           0.279174  ...             -0.047663
4           0.276629  ...             -0.043892

[5 rows x 238 columns]

In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier 

dt = DecisionTreeClassifier()
rf = RandomForestClassifier()
xt = ExtraTreesClassifier()
kn = KNeighborsClassifier()
lr = LogisticRegression(random_state=0)
svc = SVC(random_state=0, probability=True)
eclf = EnsembleVoteClassifier(clfs=[dt, rf, xt, kn, lr, svc],
                              weights=[2, 1, 1, 1, 1, 1], voting='soft')

def evaluateclf(clf):
    scores = cross_val_score(clf, columnsData, enc_training_labels)
    avg = scores.mean()
    return "performances: {}, \nAverage: {}".format(scores, avg)

print "Decision Tree {}".format(evaluateclf(dt))
print "Random Forest {}".format(evaluateclf(rf))
print "Extra Trees {}".format(evaluateclf(xt))
print "K Neighbors {}".format(evaluateclf(kn))
print "Logistic Regression {}".format(evaluateclf(lr))
print "SVC {}".format(evaluateclf(svc))
print "EnsembleVoteClassifier {}".format(evaluateclf(eclf))

Decision Tree performances: [0.17292007 0.17659054 0.17769608], 
Average: 0.175735560673
Random Forest performances: [0.17088091 0.18433931 0.19321895], 
Average: 0.182813060878
Extra Trees performances: [0.16557912 0.16353997 0.16911765], 
Average: 0.166078911173
K Neighbors performances: [0.18066884 0.16721044 0.17034314], 
Average: 0.172740806491
Logistic Regression performances: [0.18066884 0.16598695 0.17687908], 
Average: 0.174511625386
SVC performances: [0.19249592 0.18760196 0.18954248], 
Average: 0.189880120981
EnsembleVoteClassifier performances: [0.17659054 0.17577488 0.17728758], 
Average: 0.176550999229
